apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datahub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.datahub.name }}
spec:
  replicas: {{ .Values.global.component.datahub.replicaCount }}
  selector:
    matchLabels:
      app: alameda
      component: {{ .Values.global.component.datahub.name }}
  template:
    metadata:
      labels:
        app: alameda
        component: {{ .Values.global.component.datahub.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALAMEDA_DATAHUB_INFLUXDB_ADDRESS
              value: "{{ .Values.global.component.datahub.influxdbConfig.scheme }}://{{ .Values.global.component.datahub.influxdbConfig.svcName }}.{{ .Release.Namespace }}.svc:{{ .Values.global.component.datahub.influxdbConfig.port }}"
            - name: ALAMEDA_DATAHUB_INFLUXDB_USERNAME
              value: "{{ .Values.global.component.datahub.influxdbConfig.username }}"
            - name: ALAMEDA_DATAHUB_INFLUXDB_PASSWORD
              value: "{{ .Values.global.component.datahub.influxdbConfig.password }}"
            - name: ALAMEDA_DATAHUB_PROMETHEUS_TLSCONFIG_INSECURESKIPVERIFY
              value: "{{ .Values.global.component.datahub.prometheusConfig.insecureSkipVerify }}"
            - name: ALAMEDA_DATAHUB_PROMETHEUS_BEARERTOKENFILE
              value: "{{ .Values.global.component.datahub.prometheusConfig.bearerTokenFile }}"
            - name: ALAMEDA_DATAHUB_PROMETHEUS_URL
              value: "{{ .Values.global.component.datahub.prometheusConfig.scheme }}://{{ .Values.global.component.datahub.prometheusConfig.url }}:{{ .Values.global.component.datahub.prometheusConfig.port }}"
            - name: ALAMEDA_DATAHUB_RABBITMQ_URL
              value: "amqp://{{ .Values.global.component.aidispatcher.rabbitmqConfig.username }}:{{ .Values.global.component.aidispatcher.rabbitmqConfig.password }}@{{ .Values.global.component.aidispatcher.rabbitmqConfig.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.aidispatcher.rabbitmqConfig.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/datahub
              - probe
              - --type=readiness
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/datahub
              - probe
              - --type=liveness
            initialDelaySeconds: 5
            periodSeconds: 5
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "datahub.fullname" . }}-imagepull
    {{- end }}
    {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ include "datahub.fullname" . }}
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
